#+title: Loiuse Manhoo
#+author: Kevo "Piedmont" Akimbo
#+options: title:nil author:nil toc:nil
#+latex_header: \usepackage{tikz}
#+latex_header: \usepackage{geometry}

\thispagestyle{empty}
 \begin{tikzpicture}[remember picture,overlay]
   \node at (current page.center) {\fbox{\includegraphics[width=\pdfpagewidth,height=\pdfpageheight]{cover-final.png}}};
 \end{tikzpicture}
\clearpage
\thispagestyle{empty}
 \begin{tikzpicture}[remember picture,overlay]
   \node at (current page.center) {\fbox{\includegraphics[width=\pdfpagewidth,height=\pdfpageheight]{2nd-page.png}}};
 \end{tikzpicture}
\clearpage

#+TOC: headlines 2
\pagebreak
#+begin_center
I've lived eternally in antiquity.

Hopes of novel crushed by immortality.

Now a new face I must cast.

6 years but a distant past.

Forgotten by thought "not to last".
#+end_center

Those who seek to live life anew lose the importance of the present. The promise of temporary blinds one to see only a distant future. Thoughts of linearity become absent. The imagination reels itself an unignorable lure. To not age may very well mean to not be new, bound forever by adjectives of the past, yet every six years, I don a new face.

Recently I have noticed a pattern in what degree of concern I place in my current life. At the tail end of my identity, I lose most senses of preservation. Knowing another end is near, it makes me think only of what's to come.

I used to think this effect was beneficial, after all, why must I put effort into what is already fleeting. Constantly thinking of the future allows me to plot in significant detail my new life. Judging by my wording you can guess I concluded the contrary.

This state of mind (thinking of what is fleeting) appears earlier and earlier. I think of it even if it's too early for a plan to be practical. I know that I am losing my ability to live fulfilled. I worry that one day I conclude that what is momentary is ultimately useless, leaving me in eternal loneliness being the last pin of permanence in a world hugely temporary.

* Chapter 1
